In [1]:
import pandas as pd

In [2]:
# Load data files
customer_feedback = pd.read_csv('/Users/prajwalnikhar/Downloads/archive/blinkit_customer_feedback.csv')
customers = pd.read_csv('/Users/prajwalnikhar/Downloads/archive/blinkit_customers.csv')
marketing = pd.read_csv('/Users/prajwalnikhar/Downloads/archive/blinkit_marketing_performance.csv')
order_items = pd.read_csv('/Users/prajwalnikhar/Downloads/archive/blinkit_order_items.csv')
orders = pd.read_csv('/Users/prajwalnikhar/Downloads/archive/blinkit_orders.csv')
products = pd.read_csv('/Users/prajwalnikhar/Downloads/archive/blinkit_products.csv')

In [3]:
customer_feedback.head(8)

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date
0,2234710,1961864118,30065862,4,"It was okay, nothing special.",Delivery,Neutral,2024-07-17
1,5450964,1549769649,9573071,3,The order was incorrect.,App Experience,Negative,2024-05-28
2,482108,9185164487,45477575,3,"It was okay, nothing special.",App Experience,Neutral,2024-09-23
3,4823104,9644738826,88067569,4,The product met my expectations.,App Experience,Neutral,2023-11-24
4,3537464,5427684290,83298567,3,Product was damaged during delivery.,Delivery,Negative,2023-11-20
5,4089724,3265154092,43367112,2,Product was damaged during delivery.,Customer Service,Negative,2023-03-18
6,230696,4898355547,13284996,4,Highly recommended!,Product Quality,Positive,2023-04-16
7,2259308,6568151549,88866835,2,I had a bad experience.,App Experience,Negative,2024-03-31

In [4]:
# Merge order_items with products on product_id
orders_items = pd.merge(order_items, orders, on='order_id', how='left')

In [5]:
# Step 2: Add product information by merging products on 'product_id'
orders_items_products = pd.merge(orders_items, products, on='product_id', how='left')

In [6]:
# Step 3: Combine feedback with customers on 'customer_id'
feedback_customers = pd.merge(customer_feedback, customers, on='customer_id', how='left')

In [7]:
# Step 4: Merge the above feedback_customers with orders on 'order_id' to get order data aligned with feedback and customers
feedback_customers_orders = pd.merge(feedback_customers, orders, on='order_id', how='left', suffixes=('', '_order'))

In [8]:
# Step 5: Combine feedback_customers_orders with order_items subset (removing overlapping columns from orders to avoid duplicates)
# Identify columns from order_items not in orders to avoid duplicate columns
order_items_extra_cols = order_items.columns.difference(orders.columns).tolist()
order_items_subset = order_items[['order_id'] + order_items_extra_cols]

final_dataset = pd.merge(feedback_customers_orders, order_items_subset, on='order_id', how='left')

In [9]:
# Step 6: Add product details again for those order items (if needed)
final_dataset = pd.merge(final_dataset, products, on='product_id', how='left')

In [10]:
# Save the merged dataset (for further analysis or Tableau)
blinkit_df = final_dataset.to_csv('/Users/prajwalnikhar/Downloads/blinkit_final_merged.csv', index=False, header=True)
print("File saved successfully at /Users/prajwalnikhar/Downloads/blinkit_final_merged.csv")

File saved successfully at /Users/prajwalnikhar/Downloads/blinkit_final_merged.csv

In [11]:
# Preview the final dataset
print(f"Final dataset shape: {final_dataset.shape}")
print(final_dataset.head())

Final dataset shape: (5000, 39)
   feedback_id    order_id  customer_id  rating  \
0      2234710  1961864118     30065862       4
1      5450964  1549769649      9573071       3
2       482108  9185164487     45477575       3
3      4823104  9644738826     88067569       4
4      3537464  5427684290     83298567       3

                          feedback_text feedback_category sentiment  \
0         It was okay, nothing special.          Delivery   Neutral
1              The order was incorrect.    App Experience  Negative
2         It was okay, nothing special.    App Experience   Neutral
3      The product met my expectations.    App Experience   Neutral
4  Product was damaged during delivery.          Delivery  Negative

  feedback_date     customer_name                     email  ...  unit_price  \
0    2024-07-17   Urishilla Hegde          ydeo@example.org  ...      517.03
1    2024-05-28     Ranveer Mahal        phegde@example.org  ...      881.42
2    2024-09-23        Aarna Bawa  kondajagdish@example.com  ...      923.84
3    2023-11-24   Aayush Sengupta       lekha10@example.com  ...      874.78
4    2023-11-20  Vansha Kuruvilla       xalak62@example.com  ...      976.55

   product_name              category         brand   price      mrp  \
0    Pet Treats              Pet Care  Pillay-Ahuja  517.03   795.43
1  Orange Juice  Cold Drinks & Juices  Baral-Kamdar  881.42  1259.17
2          Eggs     Dairy & Breakfast    Prasad LLC  923.84  1154.80
3  Orange Juice  Cold Drinks & Juices     Gupta Ltd  874.78  1249.69
4          Nuts     Snacks & Munchies      Bahl-Pau  976.55  1502.38

   margin_percentage  shelf_life_days  min_stock_level max_stock_level
0               35.0              365               16              57
1               30.0              180               19              65
2               20.0                7               13              62
3               30.0              180               21              90
4               35.0               90               12              75

[5 rows x 39 columns]

In [16]:
blinkit_df = pd.read_csv('/Users/prajwalnikhar/Downloads/blinkit_final_merged.csv', index_col = 0)
blinkit_df.head()

,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date,customer_name,email,phone,...,unit_price,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
feedback_id,,,,,,,,,,,,,,,,,,,,,
2234710,1961864118,30065862,4,"It was okay, nothing special.",Delivery,Neutral,2024-07-17,Urishilla Hegde,ydeo@example.org,910400446367,...,517.03,Pet Treats,Pet Care,Pillay-Ahuja,517.03,795.43,35.0,365,16,57
5450964,1549769649,9573071,3,The order was incorrect.,App Experience,Negative,2024-05-28,Ranveer Mahal,phegde@example.org,912292591574,...,881.42,Orange Juice,Cold Drinks & Juices,Baral-Kamdar,881.42,1259.17,30.0,180,19,65
482108,9185164487,45477575,3,"It was okay, nothing special.",App Experience,Neutral,2024-09-23,Aarna Bawa,kondajagdish@example.com,912719661653,...,923.84,Eggs,Dairy & Breakfast,Prasad LLC,923.84,1154.80,20.0,7,13,62
4823104,9644738826,88067569,4,The product met my expectations.,App Experience,Neutral,2023-11-24,Aayush Sengupta,lekha10@example.com,913367647372,...,874.78,Orange Juice,Cold Drinks & Juices,Gupta Ltd,874.78,1249.69,30.0,180,21,90
3537464,5427684290,83298567,3,Product was damaged during delivery.,Delivery,Negative,2023-11-20,Vansha Kuruvilla,xalak62@example.com,912910638833,...,976.55,Nuts,Snacks & Munchies,Bahl-Pau,976.55,1502.38,35.0,90,12,75